### ISSUE TITLE
Bug: `The unauthenticated git protocol on port 9418 is no longer supported.`

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/BumpStdlibs.jl#69]
```
Cloning into 'STDLIB'...
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```

E.g. https://github.com/JuliaLang/BumpStdlibs.jl/actions/runs/1412783247

**Comment by DilumAluthge** [comment]
@StefanKarpinski This is why your bump failed.

**Comment by DilumAluthge** [comment]
Fix PR: https://github.com/JuliaLang/julia/pull/42906

**Comment by DilumAluthge** [comment]
Question: why are we seeing this particular failure right now?

Answer: apparently today (November 2, 2021) is the "first brownout" as discussed in the blog post: https://github.blog/2021-09-01-improving-git-protocol-security-github/#when-are-these-changes-effective

**Comment by DilumAluthge** [comment]
@StefanKarpinski This should be fixed now. I saw that you and Jameson are making more PRs to Downloads.jl, so I decided not to trigger a bump, since I wasn't sure if you guys are ready to bump yet.

**Comment by StefanKarpinski** [comment]
Thanks, I'll bump when we're done iterating.
