### ISSUE TITLE
Don't close PRs for different branches

### ISSUE THREAD

**Issue by IanButterworth** [JuliaLang/BumpStdlibs.jl#87]
This shouldn't have been closed given it targets master https://github.com/JuliaLang/julia/pull/48091#event-8162689988

**Comment by DilumAluthge** [comment]
Note to self: I think when we get the PR from the GitHub API, it should already include the target branch name somewhere in the JSON struct, so it should be sufficient to just check that, and skip closing the PR if the target branch of the PR is not equal to the desired target branch provided by the user.
